global_defs {
    router_id RTR-1
    vrrp_skip_check_adv_addr
    vrrp_garp_interval 0
    vrrp_gna_interval 0
}

vrrp_script chk_gateway_min {
    script "ping -c 1 -W 5 <isp_ip> > /dev/null 2>&1"
    interval 60
    weight -15
    fall 1
    rise 1
}

vrrp_instance VI_10 {
    state MASTER
    interface ens20.10
    virtual_router_id 10
    priority 115
    advert_int 1
    preempt yes
    authentication {
        auth_type PASS
        auth_pass vlan10_secret
    }
    virtual_ipaddress {
        <vip.10> dev ens20.10
    }
    track_script {
        chk_gateway_min
    }
}

vrrp_instance VI_20 {
    state BACKUP
    interface ens20.20
    virtual_router_id 20
    priority 100
    advert_int 1
    preempt yes
    authentication {
        auth_type PASS
        auth_pass vlan20_secret
    }
    virtual_ipaddress {
        <vip.20> dev ens20.20
    }
    track_script {
        chk_gateway_min
    }
}

vrrp_instance VI_30 {
    state MASTER
    interface ens20.30
    virtual_router_id 30
    priority 115
    advert_int 1
    preempt yes
    authentication {
        auth_type PASS
        auth_pass vlan30_secret
    }
    virtual_ipaddress {
        <vip.30> dev ens20.30
    }
    track_script {
        chk_gateway_min
    }
}
